### ISSUE TITLE
Support hook into auth interceptor (e.g. zones)

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/skyux-http#16]
This is a tracking issue to support hooking into the `SkyAuthInterceptor` in order for consumers to be able to dynamically provide URLs for `HttpClient` to use (e.g., for a given zone to point to a specific URL).

Consumers will provide the implementation and the `SkyAuthInterceptor` will detect if provided and transparently call to swap the URLs, otherwise do nothing. The `ZoneLookupProvider` will be provided by consumers to define how a zone maps to a specific URL.

**Comment by Blackbaud-PaulCrowder** [comment]
https://github.com/blackbaud/skyux-http/pull/17
