### ISSUE TITLE
Surface BBAuthGetTokenArgs from skyux/http

### ISSUE THREAD

**Issue by Blackbaud-MatthewMiles** [blackbaud/skyux-http#38]
### Expected behavior
I think BBAuthGetTokenArgs should be an accessible interface from skyux/http so that it can be referenced when calling getDecodedToken.

### Actual behavior
Currently, someone would have to reference this from the auth client, which I believe we are trying to abstract from.

**Comment by Blackbaud-MatthewMiles** [comment]
For **getDecodedToken** within class **SkyAuthTokenProvider**, the parameter is 'args?: BBAuthGetTokenArgs'.  This interface is not exported from @skyux/http.

**Comment by Blackbaud-MatthewMiles** [comment]
@Blackbaud-SteveBrush let me know how I can help describe this further.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-MatthewMiles Thanks for the additional details! We're working on a solution now.
